### ISSUE TITLE
SyntaxError: invalid syntax line 73

### ISSUE THREAD

**Issue by iwikus** [redcode-labs/VTSCAN#6]
python3 /usr/local/bin/vtscan.py
  File "/usr/local/bin/vtscan.py", line 73
    print(f"{green('[+]')} Results for {bold(res.FILE)} ({resp.json()['scan_date']})")
                                                                                    ^
SyntaxError: invalid syntax

Same with python3.5

**Comment by wintrmvte** [comment]
f() formatting function is not present in Python 3.5

**Comment by iwikus** [comment]
Maybe then put into requirements.txt which python version is required.

**Comment by wintrmvte** [comment]
Please try running it using Python > 3.6 and paste the output
