### ISSUE TITLE
Save JSON response to a file

### ISSUE THREAD

**Issue by plegrand1** [redcode-labs/VTSCAN#7]
Hello,
i'm testing this script and i cant make it save result in a json file.
What is the syntax for that ?

**python3 vtscan.py -o -k xxxxxxxxxx file.exe** 
[*] Sent file to VT api
Traceback (most recent call last):
  File "/home/pascal/Bureau/vtscan.py", line 110, in <module>
    main()
  File "/home/pascal/Bureau/vtscan.py", line 52, in main
    with open(res.OUT, "w+") as outfile:
io.UnsupportedOperation: File or stream is not seekable.

**python3 vtscan.py -o -k xxxxxxxxxx file.exe -o 1.json file.exe** 
usage: vtscan.py [-h] [-k <api_key>] [-q] [-p] [-o] [-c] FILE
vtscan.py: error: unrecognized arguments: file.exe

Thanks for your help

**Comment by wintrmvte** [comment]
If the above doesn't work, it is possible that I didn't declare the output flag within argparse correctly. Gonna check this out :3

**Comment by plegrand1** [comment]
Hello,
thanks for your answer.
It doesnt works : 
`python3 vtscan.py -o out.json -k xxxxxxxxxx file.exe`

> usage: vtscan.py [-h] [-k <api_key>] [-q] [-p] [-o] [-c] FILE
> vtscan.py: error: unrecognized arguments: CPAU.exe
